#USAR IMAGEN DEL JDK A USAR(DEBE SER DE LA MISMA VERSION DEL JDK QUE USAR EL PROYECTO)
FROM maven:3.9.4-amazoncorretto-21

#CREANDO EL DIRECTORIO RAIZ
WORKDIR /root

#COPIAR Y PEGAR ARCHIVO AL CONTENEDOR
COPY ./pom.xml /root
COPY ./.mvn /root/.mvn
COPY ./mvnw /root

#DESCARGANDO LA DEPENDECIAS DEL PROYECTO DENTRO DEL CONTENEDOR
RUN ./mvnw dependency:go-offline

#COPIAR Y PEGAR EL CODIGO FUENTE EN EL CONTENEDOR
COPY ./src /root/src

#CONSTRUYE NUESTRA APLICACION
RUN ./mvnw clean install -DskipTests

#EXPONE EL PUERTO
EXPOSE 9090

#LEVANTAR NUESTRA APLICACION DESDE EL CONTENEDOR
ENTRYPOINT ["java", "-jar","/root/target/mcc-tienda-demo-0.0.1-SNAPSHOT.jar"]

#CREAR IMAGEN: docker build -t "nombre de imagen" .